name: RunesSay
main: com.hetag.runessay.RunesSay
version: ${project.version}
api-version: 1.13
authors: ['_Hetag1216_']
commands:
  rs:
    usage: /<command>
    description: RS main command
permissions:
  runessay.command.admin: 
    default: op
    description: Access to all commands.
    children:
      runessay.command.list: true
      runessay.command.say: true
      runessay.command.version: true
      runessay.language.*: true
  runessay.language.elderfuthark: 
   default: true
   description: Grants access to the elderfuthark language
